### ISSUE TITLE
Win10无法运行程序，双击程序无反应

### ISSUE THREAD

**Issue by lmc999** [JerryAJ/node-tap-gui#1]
分别在两台Win10上测试，都是双击程序后无反应，任务进程里面也看不到程序运行。

**Comment by EjiHuang** [comment]
您好，最近有点忙，发现在最新版Win10上确实无法运行本程序，我已经重新编译发布了新版。
https://github.com/JerryAJ/node-tap-gui/releases/tag/1.0.5
